const { exportModules } = require('../core/baseExportFSModule.js');
const path = require('path');

const mongoQueries = exportModules(path.join(__dirname, './functions'));

module.exports = {
  updateActivity: mongoQueries.baseActivityQueries.updateActivity,
  getActivity: mongoQueries.baseActivityQueries.getActivity,
  getAllActivity: mongoQueries.baseActivityQueries.getAllActivity,
  deleteActivityWeek: mongoQueries.baseActivityQueries.deleteActivityWeek,
  getAllActivityWeeks: mongoQueries.baseActivityQueries.getAllActivityWeeks,
  createLeave: mongoQueries.userLeaveQueries.createLeave,
  updateLeaveReason: mongoQueries.userLeaveQueries.updateLeaveReason,
  getLeave: mongoQueries.userLeaveQueries.getLeave,
  getAvailableCallsign: mongoQueries.callsignUpdateQueries.getAvailableCallsign,
  updateCallsign: mongoQueries.callsignUpdateQueries.updateCallsign,
  getProfileAcademician: mongoQueries.acProfileQueries.getProfileAcademician,
  getAcademicieni: mongoQueries.acProfileQueries.getAcademicieni,
  createProfileAcademician: mongoQueries.acProfileQueries.createProfileAcademician,
  deleteProfileAcademician: mongoQueries.acProfileQueries.deleteProfileAcademician,
  setCooldownAcademie: mongoQueries.acProfileQueries.setCooldownAcademie,
  createProfile: mongoQueries.baseProfileQueries.createProfile,
  deleteProfile: mongoQueries.baseProfileQueries.deleteProfile,
  getProfile: mongoQueries.baseProfileQueries.getProfile,
  getProfileByCallsign: mongoQueries.baseProfileQueries.getProfileByCallsign,
  getAllMembers: mongoQueries.bulkQueries.getAllMembers,
  hasCertificate: mongoQueries.profileDocumentChecks.hasCertificate,
  hasFunc: mongoQueries.profileDocumentChecks.hasFunc,
  updateProfileName: mongoQueries.profileUpdateQueries.updateProfileName,
  updateProfileIDServer: mongoQueries.profileUpdateQueries.updateProfileIDServer,
  updateProfileIDDiscord: mongoQueries.profileUpdateQueries.updateProfileIDDiscord,
  updateProfileEntryDate: mongoQueries.profileUpdateQueries.updateProfileEntryDate,
  updateProfileCallsign: mongoQueries.profileUpdateQueries.updateProfileCallsign,
  updateProfileRank: mongoQueries.profileUpdateQueries.updateProfileRank,
  updateProfileDate: mongoQueries.profileUpdateQueries.updateProfileDate,
  updateCertificate: mongoQueries.profileUpdateQueries.updateCertificate,
  addFunc: mongoQueries.profileUpdateQueries.addFunc,
  removeFunc: mongoQueries.profileUpdateQueries.removeFunc,
  addSanctionsM: mongoQueries.profileUpdateQueries.addSanctionsM,
  addAvM: mongoQueries.profileUpdateQueries.addAvM,
  createMemberSnapshot: mongoQueries.userSnapshotQueries.createMemberSnapshot,
  getUserSnapshot: mongoQueries.userSnapshotQueries.getUserSnapshot,
  getUserSnapshots: mongoQueries.userSnapshotQueries.getMemberSnapshots,
  loadMemberSnapshot: mongoQueries.userSnapshotQueries.loadMemberSnapshot,
  deleteMemberSnapshot: mongoQueries.userSnapshotQueries.deleteMemberSnapshot,
  hasSession: mongoQueries.sessionChecks.hasSession,
  getUserSessions: mongoQueries.sessionChecks.getUserSessions,
  createSession: mongoQueries.sessionUpdateQueries.createSession,
  endSession: mongoQueries.sessionUpdateQueries.endSession,
  createComponent: mongoQueries.componentQueries.createComponent,
  getComponent: mongoQueries.componentQueries.getComponent,
  disableComponent: mongoQueries.componentQueries.disableComponent,
  addCooldown: mongoQueries.cooldownQueries.addCooldown,
  getCooldown: mongoQueries.cooldownQueries.getCooldown,
  hasCooldown: mongoQueries.cooldownQueries.hasCooldown,
  createEntryList: mongoQueries.entryListQueries.createEntryList,
  getEntryList: mongoQueries.entryListQueries.getEntryList,
  deleteEntryList: mongoQueries.entryListQueries.deleteEntryList,
  createLog: mongoQueries.logQueries.createLog,
  getTests: mongoQueries.logQueries.getTests,
  getRemoved: mongoQueries.logQueries.getRemoved,
  getTestsApproved: mongoQueries.logQueries.getTestsApproved,
  getTestsRejected: mongoQueries.logQueries.getTestsRejected,
  getFuncActivity: mongoQueries.logQueries.getFuncActivity,
  createSanction: mongoQueries.sanctionDBQueries.createSanction,
  updateSanctionList: mongoQueries.sanctionDBQueries.updateSanctionList,
  updateSanctionReason: mongoQueries.sanctionDBQueries.updateSanctionReason,
  closeSanctionList: mongoQueries.sanctionDBQueries.closeSanctionList,
  closeSanction: mongoQueries.sanctionDBQueries.closeSanction,
  getSanction: mongoQueries.sanctionDBQueries.getSanction,
  createToken: mongoQueries.tokenQueries.createToken,
  deleteToken: mongoQueries.tokenQueries.deleteToken,
  getToken: mongoQueries.tokenQueries.getToken,
  wipeSanctions: mongoQueries.bulkQueries.wipeSanctions,
}